### ISSUE TITLE
Sharp dependency

### ISSUE THREAD

**Issue by wiesson** [astro-community/astro-compress#103]
I got some build errors on vercel because of the Sharp dependency. I'm not using any sharp related features, would it be possible to remove it? I'm also not sure if it works with the Edge runtime but I'll have to verify that.

**Comment by Hans5958** [comment]
I have the same issue. Downgrading Sharp to 0.31.3 would make it work again. It seems that Sharp needs to be updated to 0.32.0 to be in sync with the peer dependency that the latest version of Astro uses.

**Comment by nikolaxhristov** [comment]
You can try the no-sharp branch https://github.com/astro-community/astro-compress/tree/no-sharp

```bash
npm install -D -E astro-community/astro-compress#no-sharp
```

**Comment by nikolaxhristov** [comment]
Hope this helps!
