### ISSUE TITLE
How can we configure a utility?

### ISSUE THREAD

**Issue by kireerik** [astro-community/astro-compress#132]
Using `compress({js: {comments: false}})` I am getting the following error when executing `astro build`:

```
Error: Cannot compress file <filepath>!
```

&nbsp;
> Using `compress()` (or `compress({js: true})`) works, but there are `some` comments (as expected since `some` is the default setting).

**Comment by nikolaxhristov** [comment]
Interesting, I'll look into it.

**Comment by kireerik** [comment]
I can't seem to find you on Discord like that. Maybe it is easier to ask for more information here.

**Comment by kireerik** [comment]
I sent a friend request.

**Comment by kireerik** [comment]
This [terser](https://terser.org/) setting goes under the `format` options.

So it works like this as expected: `compress({js: {format: {comments: false}}})`

**Comment by kireerik** [comment]
> This is not a bug.
