### ISSUE TITLE
HTML // Comments in JS Scripts Problematic

### ISSUE THREAD

**Issue by NeilCresswell** [astro-community/astro-compress#150]
Am finding that HTML .astro pages that have embedded JS in the body via <script> tags are very problematic, especially if there are comments inside starting with //, which can cause the script contents to get dropped. Workaround is to have html:false in the config file. Everything else seems good if all other settings set to true.

**Comment by NicholasJoyChrist** [comment]
Thank you for reporting this.

**Comment by NicholasJoyChrist** [comment]
Can you try `processScripts: [ ]` like this:

```ts
import compress from "astro-compress";
import { defineConfig } from "astro/config";

export default defineConfig({
	integrations: [
		compress({
			html: {
				processScripts: []
			},
		}),
	],
});
```

**Comment by NicholasJoyChrist** [comment]
or maybe `minifyJS: false`

```ts
import compress from "astro-compress";
import { defineConfig } from "astro/config";

export default defineConfig({
	integrations: [
		compress({
			html: {
				minifyJS: false
			},
		}),
	],
});
```

**Comment by NikolaRHristov** [comment]
@NeilCresswell Sorry this is my alt, but yeah what he said.

**Comment by NeilCresswell** [comment]
> Can you try `processScripts: [ ]` like so:
> 
> ```ts
> import compress from "astro-compress";
> import { defineConfig } from "astro/config";
> 
> export default defineConfig({
> 	integrations: [
> 		compress({
> 			html: {
> 				processScripts: []
> 			},
> 		}),
> 	],
> });
> ```

Only lightly tested by changing config in a small project that had the issue I originally reported. This worked and I wasn't missing JS due to // comments.

**Comment by NeilCresswell** [comment]
> or maybe `minifyJS: false`
> 
> ```ts
> import compress from "astro-compress";
> import { defineConfig } from "astro/config";
> 
> export default defineConfig({
> 	integrations: [
> 		compress({
> 			html: {
> 				minifyJS: false
> 			},
> 		}),
> 	],
> });
> ```

Problem is still present trying this way.

**Comment by NikolaRHristov** [comment]
It might be that the HTML minification is triggered before the inside script minification and that's why when it tries to compress the JavaScript inside the script tag it's just one long string with an `//` at the beginning. This is an `html-minifier-terser` thing, but I'll try to see if I can get it sorted.

**Comment by NeilCresswell** [comment]
Would the `html: {processScripts: []}` option be a better workaround choice for now than `html: false` if we want to maximize the compression?

**Comment by NikolaRHristov** [comment]
> 

Yes.

**Comment by NikolaRHristov** [comment]
You could also do block comment to avoid the minification of the whole line.

```ts
/**
 * Example
 */
```

**Comment by NikolaRHristov** [comment]
If this issue is resolved I'll close it down, feel free to re-open it whenever you have questions.

**Comment by NeilCresswell** [comment]
FWIW not resolved. Just have a work-around. Bug is still present.

**Comment by NikolaRHristov** [comment]
I am sorry, this can't get fixed. This is standard behavior in `html-minifier-terser` and the default value of `processScripts` is `[ ]` there. However, `astro-compress` is a bit more opinionated and aggressive. This is why you should use the workaround.

**Comment by NikolaRHristov** [comment]
And if you're using block comments, instead of line comments (because your minifying the file), you'll get no errors.
