### ISSUE TITLE
exclude Option not working

### ISSUE THREAD

**Issue by subhankar-trisetra** [astro-community/astro-compress#172]
```
compress({
exclude: [(file: string) => file.includes('/_astro/') && (file.endsWith('.png') || file.endsWith('.jpg') || file.endsWith('.jpeg'))],
}),
```
I've the above option set, yet it compresses the png files in the _astro folder

**Comment by NikolaRHristov** [comment]
Try `Exclude`. These are the current docs - https://github.com/NikolaRHristov/astro-compress, these will son be synchronized with https://github.com/astro-community/astro-compress. I'm just waiting on some permissions.

**Comment by NikolaRHristov** [comment]
@subhankar-trisetra you can also do `Image: false` to disable image compression. You can see the map in https://github.com/NikolaRHristov/astro-compress/blob/main/Source/Option/Map.ts
