### ISSUE TITLE
Removes a space which should not be removed

### ISSUE THREAD

**Issue by Anoian** [astro-community/astro-compress#36]
https://github.com/one-suedwest/onesw-website/blob/main/src/pages/index.astro

If you look at that file at line 73, astro-compress will remove the space between the "\<HiddenField />" and "an"

You can just clone that project and run "npm run build" and then open the generated index.html and you will see the issue.

I did not investigate this further, so i am sorry for the bad bug description.

I made sure that the problem does not exist when removing compress() from the vite config, so i am pretty sure that the issue is with astro-compress.

**Comment by nikolarhristov** [comment]
Use &nbsp; after the closing tag.

**Comment by nikolarhristov** [comment]
This will be fixed in `1.0.9`

**Comment by Anoian** [comment]
Thank you :)

**Comment by nikolarhristov** [comment]
Fixed in [1.0.9](https://github.com/astro-community/astro-compress/releases/tag/v1.0.9)
