### ISSUE TITLE
Option to disable image compression 

### ISSUE THREAD

**Issue by bronze** [astro-community/astro-compress#40]
Hi, ive tried the code on the readme and had `img: false` but that didnt work.
Taking a look at the code i tried `sharp: false` and it worked.
```
compress({
	css: false,
	html: false,
	js: false,
	img: false, // doesnt work
        sharp: false, // works
	svg: false,
}),
```

**Comment by nikolarhristov** [comment]
Fixed in 8420d5f78af7f76d1720651279ac226996af31bf
