### ISSUE TITLE
HTML not getting minified when using parameterless arrow functions

### ISSUE THREAD

**Issue by DevTobias** [astro-community/astro-compress#51]
Hey! :) Maybe this is an error with the html minimizer, but I dont get any errors / logs, that's why im posting this here.

Im using a minimal project with "astro": "^1.6.5" and "astro-compress": "^1.1.1"

I noticed that html files are ignored while compressing if any script contains arrow functions used like this:
```
<script>
    const sayHello = () => {
        console.log("Hello World");
    }
    sayHello();
</script>
```

However it's getting compressed with this script, which I thought was kinda weird:
```
<script>
    (() => {
        console.log("Hello World");
    })()

    function initializeTheme() {
        console.log("Hello World");
    }

    initializeTheme();
</script>
```

Whats even funnier is, that the following script (arrow function with parameters) is working too:
```
<script>
    const sayHello = (name) => {
        console.log(`Hello ${name}`);
    }
    sayHello("World");
</script>
```

To be more clear, the compressor doesn't work if any script contains arrow functions without parameters :D

**Comment by nikolaxhristov** [comment]
Can you provide a reproduction? I tried locally but Astro extracts the scripts into a different file.

**Comment by DevTobias** [comment]
Okay thats interesting, I forked the repository and debugged the html minification.

The file is not getting compressed, because this if statement fails `if (fileSizeBefore > Buffer.byteLength(writeBuffer))`

I wondered, how that could even be the case, but as it seems, something goes wrong with the js minification of inline scripts:


Before minification:
```
<!DOCTYPE html>
<script type="module">const l=()=>{console.log("Hello World")};l();
</script><h1>Hello World</h1>

<p>Hello World 2</p>
```

After minification:

```
<!DOCTYPE html><script type=module>const l=()=>{console.log("Hello World")};console.log("Hello World")</script><h1>Hello World</h1><p>Hello World 2</p>
```

Somehow, the call of the function didn't already get minified by astro. Then the html-minifier tries to compress it, but in the process does not remove the initial function, resulting in a bigger file, because the content of the function now exists two times.

**Comment by nikolaxhristov** [comment]
Ok, I'm gonna add this to the defaults:

```js
minifyJS: {
	compress: {
		reduce_vars: false,
	}
}
```

Can I close this now?

**Comment by DevTobias** [comment]
I think this is a viable workaround so you can close it :D 

I would not remove the if check, because I think it's a good feature. I mean nobody wants a compressor which enlarges files, so preventing this should still be a thing :D Maybe it also discovers more such weird terser things in the future. :D
