### ISSUE TITLE
Remove html comments on default

### ISSUE THREAD

**Issue by redwerkz** [astro-community/astro-compress#56]
from https://github.com/astro-community/astro-compress/issues/11

> I'll take a closer look at the comments one another time. But it is set to **false** for now in v0.0.17

**Comment by nikolaxhristov** [comment]
This results in hydration errors. It's some bug with the `html-minifier-terser` library https://github.com/astro-community/astro-compress/issues/11#issuecomment-1209355695. I might apply https://github.com/terser/html-minifier-terser/pull/87

**Comment by nikolaxhristov** [comment]
Fixed in https://github.com/astro-community/astro-compress/releases/tag/v1.1.8
