### ISSUE TITLE
Install error on Android (termux)

### ISSUE THREAD

**Issue by SamXuLing** [astro-community/astro-compress#57]
I'd typed `npm install -D -E astro-compress` but got error like this :
![Screenshot_20221121-183719394](https://user-images.githubusercontent.com/33863355/203160648-ffaf7b2d-908b-4545-9c13-15eb924ee311.jpg)
```
[##################] - reify:css-tree: timing reifyNode:node_modules/
> sharp@0.31.2 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-android-arm64v8.tar.br
sharp: Installation error: Prebuilt libvips 8.13.3 binaries are not yet available for android-arm64v8
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/samxuling.github.io/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
```
It say `Prebuilt libvips 8.13.3 binaries are not yet available for android-arm64v8`
Is the download address incorrect? 🤔 
When I navigated to `https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-android-arm64v8.tar.br` GitHub say `404`

**Comment by nikolaxhristov** [comment]
I don't think Sharp has support for Android :D https://github.com/lovell/sharp-libvips

**Comment by nikolaxhristov** [comment]
`astro-compress` uses [sharp](https://github.com/lovell/sharp) to compress images

**Comment by nikolaxhristov** [comment]
You can try using it on [codesanbox.io](https://codesandbox.io/) if you're on an Android phone, as it emulates the environment, instead of running it locally.

**Comment by SamXuLing** [comment]
> `astro-compress` uses [sharp](https://github.com/lovell/sharp) to compress images

How to exclude it from installation process?

**Comment by SamXuLing** [comment]
> You can try using it on [codesanbox.io](https://codesandbox.io/) if you're on an Android phone, as it emulates the environment, instead of running it locally.

I want to publish to my GitHub Pages not doing experiment on [codesandbox](https://codesandbox.io/)

**Comment by nikolaxhristov** [comment]
I've cooked up a special build for you, you can try by installing `astro-compress#no-sharp` like so:

```
npm install -D -E astro-community/astro-compress#no-sharp
```

This pulls from the https://github.com/astro-community/astro-compress/tree/no-sharp branch. 😊 Hope this helps!

**Comment by nikolaxhristov** [comment]
It will still compress your other files while leaving the images alone.

**Comment by SamXuLing** [comment]
Noice! Thanks you so much! 👍 
![Screenshot_20221122-131243774](https://user-images.githubusercontent.com/33863355/203240721-d40917ab-b78f-49ff-91e1-99cf21818a2a.jpg)

**Comment by sohaha** [comment]
mac m1 seems to be doesn't support

**Comment by nikolaxhristov** [comment]
Hi, @sohaha could you open a new issue, detailing the exact report and what doesn't work?

**Comment by sohaha** [comment]
@nikolaxhristov It doesn't feel necessary, because it's also a sharp issue, and the latest version of m 1 macOS doesn't seem to be supported yet. 😀
