### ISSUE TITLE
HTML comments not being removed. NaN undefined for file count.

### ISSUE THREAD

**Issue by fabriziogiordano** [astro-community/astro-compress#60]
Since I upgraded from 1.1.7 to 1.1.12 the comments from the HTML are not being removed.

I get `NaN undefined` and comments from the html are not removed. Spacing is removed but not comments.

Astro version: `"astro": "^1.6.11"`

```
07:18:03 AM [build] Waiting for the astro-compress integration...
Successfully compressed a total of 7968 HTML files for NaN undefined.
Successfully compressed a total of 8 JS files for NaN undefined.
Successfully compressed a total of 20 SVG files for NaN undefined.
```

Here my astro.config:

```js
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import compress from "astro-compress";
import prefetch from '@astrojs/prefetch';

import { SITE_URL, SERVER_PORT } from "./src/config";

export default defineConfig({
  site: SITE_URL,
  vite: {
    server: {
      watch: {
        ignored: ["/dist/**", "/db/**", "/src/pages/days/*.md"],
      },
    },
    logLevel: 'silent'
  },
  publicDir: "./assets",
  server: {
    port: SERVER_PORT,
    // host: true
  },
  integrations: [
    prefetch(),
    sitemap(),
    compress({
      css: false,
      html: {
        removeComments: true,
        maxLineLength: 1000,
        quoteCharacter: '"',
        removeAttributeQuotes: true
      },
      img: false,
      js: true,
      svg: true,
      logger: 1,
    }),
  ],
});
```

Here a gist of the html I am trying to compress: https://gist.github.com/fabriziogiordano/83f68463ad32c9f9361cb642041a9cbb

I tried different versions and it seems it is starting from astro version 1.1.8

**Comment by nikolaxhristov** [comment]
Hi, thank you will look at it shortly!

**Comment by nikolaxhristov** [comment]
Fixed in https://github.com/astro-community/astro-compress/releases/tag/v1.1.14

**Comment by fabriziogiordano** [comment]
Thank @nikolaxhristov 
I'll update and run it to double check.

**Comment by fabriziogiordano** [comment]
it looks like NPM didn't pick it up yet. Latest is still 1.1.13

<img width="716" alt="image" src="https://user-images.githubusercontent.com/109390/204719125-3c2d9cac-8b78-47ed-b811-3bbbabce42d0.png">

**Comment by nikolaxhristov** [comment]
No, I just forgot to publish 😁

**Comment by nikolaxhristov** [comment]
Up now. @fabriziogiordano

**Comment by fabriziogiordano** [comment]
It is working now on dev. I'll run the production version and close this issue accordingly. Thank you @nikolaxhristov !

**Comment by fabriziogiordano** [comment]
It seems resolved and closing for now~
