### ISSUE TITLE
HTML Compress does not work on cloudflare workers

### ISSUE THREAD

**Issue by marchellodev** [astro-community/astro-compress#64]
Hello, does this plugin only supports node environment? It seems like when deploying to cloudflare workers HTML does not seem to be compressed

**Comment by marchellodev** [comment]
Looking at the logs, it actually seems to compress js and SVG. But the HTML remains unaffected

**Comment by nikolaxhristov** [comment]
Hi, can you provide a reproduction? Also, note that it doesn't work on SSR only SSG.

**Comment by marchellodev** [comment]
I think that actually might be the problem as the website is rendered on a Cloudflare worker. I think it should be added somewhere in the readme that SSR is not supported.

**Comment by nikolaxhristov** [comment]
Fixed in https://github.com/astro-community/astro-compress/releases/tag/v1.1.20
