### ISSUE TITLE
Compress animated webp

### ISSUE THREAD

**Issue by ColinFrick** [astro-community/astro-compress#66]
Currently compressing animated webp result in a still image instead of the animation.

Any way to supply an regexp to match animated webp files would be brilliant.

**Comment by nikolaxhristov** [comment]
I've added `animated: true` to the [`animated`](https://github.com/astro-community/astro-compress/tree/animated) branch. You can try to install with, as a temporary solution:

```bash
npm install -D -E astro-community/astro-compress#animated
```

I'll look into this further, as there are a few other problems with `webp` that do not surface on the regular.

**Comment by SimplyVoid** [comment]
had same issue with gif (& webp) images where the image becomes static after compression

**Comment by nikolaxhristov** [comment]
> also had same issue with gif (& webp) images where the image becomes static after compression

Try the animated branch: ```npm install -D -E astro-community/astro-compress#animated``` I still haven't updated `astro-compress` to detect automatically but it should work just fine.
