### ISSUE TITLE
CSS Class Reorder Issue

### ISSUE THREAD

**Issue by nicklanehq** [astro-community/astro-compress#68]
Hi,

We're having an issue on a build where astro-compress is reordering the CSS class declarations for a few DIVs where the order is critical to the responsive nature of the element. The site is using Bootstrap where class ordering for showing/hiding an DOM element on mobile matters. Compress is reordering all classes to be alphabetical (from what we're noticing which breaks our logic). Is there a way to disable this type of cleanup process?

Thanks!

**Comment by nikolaxhristov** [comment]
Yeah, I'm sure if you set `sortClassName` to `false` everything will be alright: 

```ts
compress({
	html: {
		sortClassName: false
	}
})
```

**Comment by nicklanehq** [comment]
Thanks! That helped with the HTML output. 

We noticed it was also compiling CSS compression with the same breaking order issue. We found and applied the restructure: false config setting from the CSSO docs.

Applying both resolved our issue.

`compress({
      css: {
        restructure: false
      },
     html: {
        sortClassName: false
      }
})`
