### ISSUE TITLE
Switch compress off on development mode

### ISSUE THREAD

**Issue by redwerkz** [astro-community/astro-compress#76]
for better debugging switch it off in dev mode
import.meta.env.MODE === "production" ? compress() : compress({html: false}) },

**Comment by nikolaxhristov** [comment]
Neat, I'll pin this issue as the user can configure this in their `astro.config.ts` file.

**Comment by nikolaxhristov** [comment]
Hi, @rdwz, compress will not get triggered in either case, because the website is always rendered from vite SSR if using dev, unless you modify that variable explicitly through a NODE environment variable.
