### ISSUE TITLE
Use Astro `config.outDir` as default instead of `files-pipeline` default

### ISSUE THREAD

**Issue by johnzanussi** [astro-community/astro-compress#78]
I noticed the following in the docs.

> If your path is different than dist be sure to update it accordingly:
```js
// astro.config.ts

import compress from "astro-compress";

export default {
	outDir: "./build",
	integrations: [
		compress({
			path: "./build",
		}),
	],
};
```

While I agree that allowing users to manually override the `path` option is necessary, other Astro integrations + adapters may change the output directory using the `outDir` config property. Without digging into third-party integration/adapter code, it isn't obvious that that value has changed.  

An example of this is the official `@astrojs/vercel` adapter that modifies the `outDir` property.

https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/static/adapter.ts#L19

Looking through the code of this integration it looks like it sets the default value of `path` to `./dist`, which comes from the [`files-pipeline` defaults](https://github.com/lightrix/files-pipeline/blob/main/src/options/index.ts#L77). 

I propose using the value of `config.outDir` from Astro as the default instead. This allows seamless integration with other third-party integrations/adapters and, if Astro ever changes its default value, keeps this integration working without needing a code change.

I'm happy to open a PR with this change if ya'll are accepting them.

**Comment by nikolaxhristov** [comment]
Approved!

**Comment by nikolaxhristov** [comment]
PRs are welcome! @johnzanussi

**Comment by nikolaxhristov** [comment]
There used to be a change that applied this, check https://github.com/astro-community/astro-compress/blob/863be69bbf1050408f6636fa34d70c6f8a4dcbdc/src/index.ts

**Comment by johnzanussi** [comment]
> There used to be a change that applied this, check https://github.com/astro-community/astro-compress/blob/863be69bbf1050408f6636fa34d70c6f8a4dcbdc/src/index.ts

Before I open a PR, was there a specific reason why this was removed?

**Comment by johnzanussi** [comment]
Understood. Thanks for the background info. I'll have a PR up for this today.

**Comment by johnzanussi** [comment]
PR is up

https://github.com/astro-community/astro-compress/pull/79

**Comment by nikolaxhristov** [comment]
Fixed in https://github.com/astro-community/astro-compress/releases/tag/v1.1.30
