### ISSUE TITLE
Feature request: ld-json compression in readme / examples or enabled by default

### ISSUE THREAD

**Issue by xfenix** [astro-community/astro-compress#81]
Hey, great project, thanks for your work!
I'm here for feature request. Currently, there is no ld-json compression by default. It may be not very needed for many users, but it may help someone.  As I found out here, https://github.com/terser/html-minifier-terser/issues/34 it easily enabled by `{ processScripts: ['application/ld+json'] }` configuration option. I spent some time in your README and finally be able to write something like this
```
...
    compress({
      html: {
        processScripts: ["application/ld+json"],
      },
    }),
...
```
And it works. But, this leads me to the following conclusions. It will be cool to do something of or both:
- add in your README example of options override (because, in my opinion, it not so obvious despite the phrase «You can override any of the default options from the configurations of»). It is easy to achieve and increase ease of usage of your project. Yeah, you may say this is basic thing for the software engineer to be the partially detective, but I think more obvious path in README don't kill this vibe 
- add by default this option (it wouldn't harm anyone, I think?)

Example of compressed built HTML with untouched ld-json section (if anyone wants to see how it looks):
<img width="605" alt="image" src="https://user-images.githubusercontent.com/1441415/218897903-9ee89ef5-ea39-4054-ab03-28bd5a714f42.png">

**Comment by nikolaxhristov** [comment]
It will be added by default! Expect it in 1.1.33
