### ISSUE TITLE
Add sample default override in README.md

### ISSUE THREAD

**Issue by thdoan** [astro-community/astro-compress#98]
I read that "you can override any of the default options from the configurations," but I am not sure how to go about doing this. It would be helpful if you can add an example of how to override a default (e.g., `keepClosingSlash: true` for html-minifier-terser) in README.md.

**Comment by thdoan** [comment]
After some experimentation, this is the way:

```
export default defineConfig({
  integrations: [
    compress({
      html: {
        keepClosingSlash: true,
      },
    })
  ],
});
```

**Comment by nikolaxhristov** [comment]
I haven't included them because the options might change and so I found a link to the original options to be better.
